version: "3"

services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: botler
        ports:
            - "5432:5432"
        volumes:
            - ./postgres_volume:/var/lib/postgresql/data

    bot:
        build:
            context: .
            dockerfile: Dockerfile.bot
        depends_on:
            - postgres